# Site settings
title: Gotbadger
email: your-email@domain.com
description: "Blog of Philip Hayton"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gotbadger
github_username:  gotbadger

# Build settings
markdown: kramdown
